#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

echo 
echo "*** Вытягиваем изменения в Prime [Hub's post-update hook]"
echo 
cd $HOME/www/assets/templates/front/ || exit
unset GIT_DIR
git pull hub master
exec git update-server-info